In [5]:
## 시계열 데이터
import pandas as pd
df = pd.read_csv("/content/stock-data.csv")
df.head()
df['timestamp_Date'] = pd.to_datetime(df['Date'])

# print(df.Date.tolist()[0] - df.Date.tolist()[1])
print(df.timestamp_Date.tolist()[0] - df.timestamp_Date.tolist()[1])



In [16]:
# 시간 데이터를 만들고 시작일 ~ 종료일
pd.date_range(start = '2020-01-01',end='2023-01-01',freq = 'MS')

DatetimeIndex(['2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01',
               '2020-05-01', '2020-06-01', '2020-07-01', '2020-08-01',
               '2020-09-01', '2020-10-01', '2020-11-01', '2020-12-01',
               '2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01',
               '2021-05-01', '2021-06-01', '2021-07-01', '2021-08-01',
               '2021-09-01', '2021-10-01', '2021-11-01', '2021-12-01',
               '2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01',
               '2022-05-01', '2022-06-01', '2022-07-01', '2022-08-01',
               '2022-09-01', '2022-10-01', '2022-11-01', '2022-12-01',
               '2023-01-01'],
              dtype='datetime64[ns]', freq='MS')

In [32]:
## Concat
import pandas as pd

df1 = pd.DataFrame({'a':['a0','a1','a2','a3'],
                   'b':['b0','b1','b2','b3'],
                   'c':['c0','c1','c2','c3']},
                  index = [0,1,2,3])

df2 = pd.DataFrame({'a':['a2','a3','a4','a5'],
                   'b':['b2','b3','b4','b5'],
                   'c':['c2','c3','c4','c5'],
                   'd':['d2','d3','d4','d5']},
                   index = [2,3,4,5])

print(df1, '\n')
print(df2)

# Concat : 이어붙이기
concat_df = pd.concat([df1,df2],ignore_index=True)
concat_df = pd.concat([df1,df2],axis=1)
concat_df = pd.concat([df1,df2],axis=1, join='inner')
concat_df

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3 

    a   b   c   d
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  a4  b4  c4  d4
5  a5  b5  c5  d5


a   b   c   a   b   c   d
2  a2  b2  c2  a2  b2  c2  d2
3  a3  b3  c3  a3  b3  c3  d3

In [43]:
## Merge
import pandas as pd

df1 = pd.DataFrame({'a':['a0','a1','a2','a3'],
                   'b':['b0','b1','b2','b3'],
                   'c':['c0','c1','c2','c3']},
                  index = [0,1,2,3])

df2 = pd.DataFrame({'a':['a2','a3','a4','a5'],
                   'b':['b2','b3','b4','b5'],
                   'c':['c2','c3','c4','c5'],
                   'd':['d2','d3','d4','d5']},
                   index = [2,3,4,5])
print(df1, '\n')
print(df2)

pd.merge(df1,df2,how='outer')

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3 

    a   b   c   d
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  a4  b4  c4  d4
5  a5  b5  c5  d5


In [50]:
df3 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df4 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

print(df3)
print(df4)
print(pd.merge(df3,df4,on='employee'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [51]:
# Join
import pandas as pd

df1 = pd.DataFrame({'a':['a0','a1','a2','a3'],
                   'b':['b0','b1','b2','b3'],
                   'c':['c0','c1','c2','c3']},
                  index = [0,1,2,3])

df2 = pd.DataFrame({'a':['a2','a3','a4','a5'],
                   'b':['b2','b3','b4','b5'],
                   'c':['c2','c3','c4','c5'],
                   'd':['d2','d3','d4','d5']},
                   index = [2,3,4,5])

df3 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df4 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

print(df1, '\n')
print(df2)

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3 

    a   b   c   d
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  a4  b4  c4  d4
5  a5  b5  c5  d5


In [ ]:
df3 = df3.set_index('employee')

In [58]:
df4 = df4.set_index('employee')

In [61]:
df3.join(df4)

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [68]:
## Glob 사용법
# 1. 파일 디렉토리 확인 /content/sample_data/
# 2. 이름을 가져오고 싶은 파일의 확장자 확인 .csv
from glob import glob
glob('/content/sample_data/*.csv')

['/content/sample_data/mnist_train_small.csv',
 '/content/sample_data/california_housing_test.csv',
 '/content/sample_data/mnist_test.csv',
 '/content/sample_data/california_housing_train.csv']

In [ ]:
## 병렬 처리 - Pool
import time, os

def work_func(x):
    print("value %s is in PID : %s" % (x, os.getpid()))
    time.sleep(1)
    return x**5

def main():
    start = int(time.time())
    print(list(map(work_func, range(0,12))))
    print("***run time(sec) :", int(time.time()) - start)


In [ ]:
import multiprocessing as mp
mp.cpu_count()

In [ ]:
import time, os
import numpy as np
import pandas as pd
from multiprocessing import Pool

def work_func(data):
    print('PID :', os.getpid())
    data['length_str'] = data['Name'].apply(lambda x : len(x))
    return data

def parallel_dataframe(df, func, num_cores):
    df_split = np.array_split(df, num_cores)
    pool = Pool(num_cores)
    df = pd.concat(pool.map(func, df_split))
    pool.close()
    pool.join()
    return df

def main():
    start = int(time.time())
    my_dir = r"D:\Python\kaggle\titanic\\"
    df = pd.read_csv(my_dir + "train.csv", dtype=str)
    num_cores = 4
    df = parallel_dataframe(df,work_func, num_cores)
    print("***run time(sec) :", int(time.time()) - start)

if __name__ == "__main__":
    main()

In [ ]:
# parallelize_test.py

import time, os
from multiprocessing import Process

def work_func(x):
    print("value %s is in PID : %s" % (x, os.getpid()))
    return x**5

def main():
    start = int(time.time())
    procs = []
    for num in range(1,10):
        proc = Process(target=work_func, args=(num,))
        procs.append(proc)
        proc.start()

    for proc in procs:
        proc.join()
    print("***run time(sec) :", int(time.time()) - start)

if __name__ == "__main__":
    main()

In [ ]:
## String Handling
## Startwith
import seaborn as sns
titanic = pd.read_csv('train.csv')

titanic.head()
titanic.dropna(inplace=True)

# .str

# String Column에 대한 Indexing
titanic['Cabin'].str[:1]

# String Column에 대한 Split
titanic['Name'].str.split(',',expand=True)

# startwith, endwith
titanic['Cabin'].str.startswith('C') # T & F

# find, rfind
titanic['Sex'].str.find('fe') # index

In [ ]:
names = titanic['Name'].str.split(',',expand=True)
names.columns = ['First_Name','Second_Name']

titanic = pd.concat([titanic, names],axis=1)

In [110]:
## Reshape
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])
print(a)
b = np.reshape(a,(2,4))
print(b)
c = np.reshape(a,(4,2))
print(c)

d = a.reshape(-1,1)
print(d)

print(b.reshape(-1))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[1 2 3 4 5 6 7 8]


In [122]:
## Basic EDA : Exploratory Data Analysis 탐색적 데이터 분석

# head & tail
titanic.head(10)
titanic.tail(10)

# shape
titanic.shape

# info
titanic.info()

# dtypes
titanic.dtypes

# describe()
titanic.describe()

# count(), value_counts()
titanic.count()
print(titanic.Sex.value_counts())

# 통계적인 값들
.sum() .mean() .median() .mode() min() max() corr()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  183 non-null    int64  
 1   Survived     183 non-null    int64  
 2   Pclass       183 non-null    int64  
 3   Name         183 non-null    object 
 4   Sex          183 non-null    object 
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64  
 7   Parch        183 non-null    int64  
 8   Ticket       183 non-null    object 
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object 
 11  Embarked     183 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB
male      95
female    88
Name: Sex, dtype: int64
